### ISSUE TITLE
quantization

### ISSUE THREAD

**Issue by qbcleo** [openvla/openvla#10]
Are the int8 and int4 quantization mentioned in the paper open source and supported in this repo

**Comment by kpertsch** [comment]
Jup, just add `load_in_8bit=True` or `load_in_4bit=True` when you load the AutoModel from HuggingFace! :)

```
vla = AutoModelForVision2Seq.from_pretrained(
    "openvla/openvla-7b", 
    attn_implementation="flash_attention_2",  # [Optional] Requires `flash_attn`
    low_cpu_mem_usage=True, 
    trust_remote_code=True,
    load_in_4bit=True,
).to("cuda:0")
```

**Comment by qbcleo** [comment]
thanks!!!










-----原始邮件-----
发件人:"Karl Pertsch" ***@***.***>
发送时间:2024-06-30 05:53:06 (星期日)
收件人: openvla/openvla ***@***.***>
抄送: qbcleo ***@***.***>, Author ***@***.***>
主题: Re: [openvla/openvla] quantization (Issue #10)






Jup, just add load_in_8bit=True or load_in_4bit=True when you load the AutoModel from HuggingFace! :)

vla = AutoModelForVision2Seq.from_pretrained(
    "openvla/openvla-7b", 
    attn_implementation="flash_attention_2",  # [Optional] Requires `flash_attn`
    low_cpu_mem_usage=True, 
    trust_remote_code=True,
    load_in_4bit=True,
).to("cuda:0")

**Comment by arashakb** [comment]
But in the paper QLoRA has been used right? what type of quantization is this?
