### ISSUE TITLE
7-DoF outputs

### ISSUE THREAD

**Issue by raymondyu5** [openvla/openvla#102]
Hi guys!

Thanks for open sourcing this amazing repo! I had a quick question regarding the 7-DoF output that OpenVLA produces. Specifically, I see in the paper that they are deltas in position, theta, and gripper action. I am wondering as to if theta is in euler angles? Just wanted to confirm since position (3) + theta (quaternion, 4) + 1 = 8.

**Comment by doggiedoggie1026** [comment]
Have you solved this problem?
