### ISSUE TITLE
ModuleNotFoundError: No module named 'dlimp' 

### ISSUE THREAD

**Issue by tekntrash** [openvla/openvla#107]
That module is nowhere to be found

**Comment by moojink** [comment]
Hi @tekntrash,

Have you completed the setup instructions in the README here? [https://github.com/openvla/openvla?tab=readme-ov-file#installation](https://github.com/openvla/openvla?tab=readme-ov-file#installation)

The `pip install -e .` step in the `openvla` base directory should download `dlimp` as it is listed as a requirement in [`pyproject.toml`](https://github.com/openvla/openvla/blob/main/pyproject.toml).

-Moo Jin

**Comment by wanxd2023** [comment]
Thank you
