### ISSUE TITLE
bridge dataset actions

### ISSUE THREAD

**Issue by ymxllife** [openvla/openvla#114]
Hi, I noticed you relabel the action labels using real traj rather than the original ones for bridge v2 dataset. Is there any specific reason?

**Comment by HomerW** [comment]
Yes, in the past I've found this action relabeling strategy combined with evaluating using blocking control results in better performance. 

During data collection the robot does not always achieve the action that was commanded, and whether it overshoots or undershoots depends on how fast the end effector is currently moving. This means the policy needs to look at a history of multiple observations to determine the best action. However we can make the learning problem simpler by using the actual change in position of the end effector as the action. Then, during evaluation, we can force the the robot to always achieve the commanded action using a blocking controller (see the flag in the bridge data evaluation script in this repo). Though this strategy comes at the cost of making the robot's motion much less fluid. For the most fluid motion, you'd want to use the original actions and evaluate with non-blocking control (though in principle your policy will need to see a history of frames to fully fit the data in this case).
