### ISSUE TITLE
How to continue training if the program is interrupted during the use of Lora training. The code script is as follows:torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \   --vla_path "/mnt/d/ll/openvla/openvla-7b" \   --data_root_dir "/mnt/d/ll/openvla/BridgeData" \   --dataset_name bridge_orig \   --run_root_dir "/mnt/d/ll/openvla/checkpoint" \   --adapter_tmp_dir "/mnt/d/ll/openvla/adapter_tmp" \   --lora_rank 32 \   --batch_size 4 \   --grad_accumulation_steps 1.5 \   --learning_rate 5e-4 \   --image_aug  False \   --wandb_project openvla142 \   --wandb_entity my \   --save_steps 1000

### ISSUE THREAD

**Issue by llll111111** [openvla/openvla#116]

**Comment by kpertsch** [comment]
We save LoRA checkpoints by merging the LoRA weights into the model backbone. So you could try simply loading the last checkpoint's weights right after creating the model, here: https://github.com/openvla/openvla/blob/46b752f477cc5773cc1234b2e82c0e2130e4e890/vla-scripts/finetune.py#L164

Our finetuning code currently does not support saving of the optimizer state though, so it's a bit experimental, but could work.
