### ISSUE TITLE
Finetuning LIBERO, TFDS DatasetNotFoundError

### ISSUE THREAD

**Issue by jis3613** [openvla/openvla#120]
Hi, I'm trying to finetune the openvla on libero dataset you provided.

However, I constantly get the following error.
` 
        - xtreme_xnli
        - yahoo_ltrc
        - yelp_polarity_reviews
        - yes_no
        - youtube_vis

Check that:
    - if dataset was added recently, it may only be available
      in `tfds-nightly`
    - the dataset name is spelled correctly
    - dataset class defines all base class abstract methods
    - the module defining the dataset class is imported

No builder could be found in the directory: datasets for the builder: libero_spatial_no_noops.
However, a folder for "libero_spatial_no_noops" does exist. Is it possible that you specified the wrong config? You can add a config by replacing `tfds.load(libero_spatial_no_noops)` by `tfds.load("libero_spatial_no_noops/my_config")`. Possible configs are:
        - 1.0.0
`

It seems like the libero dataset you modified in rlds format is not registered in the tfds.

Or are there additional steps that I need to follow ?

This is the script I ran.
`torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \ 
--vla_path openvla/openvla-7b \ 
--data_root_dir datasets \ 
--dataset_name libero_spatial_no_noops \ 
--run_root_dir runs \ 
--adapter_tmp_dir adapter_tmp_weights \ 
--lora_rank 32 \ 
--batch_size 4 \ 
--grad_accumulation_steps 4 \ 
--learning_rate 5e-4 \ 
--image_aug True \ 
--save_steps 5000 \`

datasets dir is located under openvla and libero_spatial_no_noops is located under datasts so,
`/openvla/datasets/libero_spatial_no_noops`

Your answer would be a great help to me. @kpertsch @moojink
Thanks!

**Comment by donovanclay** [comment]
Did the absolute path resolve this issue? I'm having the same issue and setting the absolute path doesn't seem to help
