### ISSUE TITLE
How can I use multi-GPU training to shorten the training time?

### ISSUE THREAD

**Issue by lidingzhe** [openvla/openvla#125]
Hello, thank you for providing such an exciting work. While studying your code, I encountered some confusion. When I ran the fine-tuning code of LIBERO_GOAL, I set ----nproc-per-node to 1, and found that the total number of batches processed by one process was 6506. However, when I set ----nproc-per-node to 2, I found that each process still processed 6506 batches. DDP distributed training should divide the total number of batches equally between each process, right? I didn’t find the DataSampler setting in the DataLoader. How can I use multi-GPU training to shorten the fine-turning time? Looking forward to your answer, thank you~

**Comment by kpertsch** [comment]
Briefly googled this: https://stackoverflow.com/questions/73899097/distributed-data-parallel-ddp-batch-size
looks like DDP does not split the batch size, but each process runs with the specified batch size and the global batch size is local_batch_size x num_processes.
So in your case, if you train with N GPUs, you can reduce the specified batch size by a factor of N and still get the same training dynamics.
