### ISSUE TITLE
Is it possible to apply LoRA finetune on a very small dataset

### ISSUE THREAD

**Issue by wzds2015** [openvla/openvla#131]
As titled. Curious if there is any conclusion on the minimum size of dataset which can be successful for LoRA finetune? If so, what's the scale, 10s, 100s, or 1000s? The reason I ask is ACT style model claims to be effective with 50 demonstrations.

**Comment by moojink** [comment]
Hi @wzds2015,

We haven't performed extensive analysis on the number of demos needed to fine-tune OpenVLA. In all of our real-world experiments, we simply made educated guesses about how many demos we would need for each task to cover most of the possible initial configurations of the environment, based on intuition from previous projects.

We did also show that we can fine-tune OpenVLA with as little as 10-50 demos in our real-world Franka Panda fine-tuning experiments (see the paper for the specific amount of demos per task, as it varies between 10-150 demos).

So yes, you can do LoRA fine-tuning with very small datasets. The exact number of demos depends on how much coverage you want over your environment / how varied your test cases will be. Make sure to enable image augmentations while fine-tuning to prevent overfitting if using very few demos!

-Moo Jin
