### ISSUE TITLE
OXE Magic Soup: pre-trained Prismatic VLM vs pre-trained LLM + pre-trained Vision Encoder

### ISSUE THREAD

**Issue by KopanevPavel** [openvla/openvla#132]
Dear authors! 
In the paper, you mentioned that the final checkpoint is for fine-tuned pre-trained Prismatic VLM. But there is also a config for Vicuña v1.5 7B + SigLIP ViT based training in the code. I was curious if you compared the results for these two scenarios:
1. Fine-tuning from pre-trained Prismatic VLM
2. Fine-tuning from pre-trained LLM + pre-trained Vision Encoder (they **were not prior fine-tuned as VLM together** e.g. on LLaVA 1.5 data mixture, and are only trained together as VLM on OXE magic soup)
Will appreciate your feedback:)

**Comment by kpertsch** [comment]
Hey!
We have not tried the experiment you described, ie all of our experiments used VLM-aligned vision + LLM backbones. Trying whether this VLM alignment step is necessary is a reasonable thing to do though!
