### ISSUE TITLE
Question about converting regenerated LIBERO HDF5 datasets to RLDS datasets

### ISSUE THREAD

**Issue by AndyCao1125** [openvla/openvla#136]
Dear authors,

Thanks for your wonderful work!

I have a question about how to convert the regenerated LIBERO HDF5 datasets to RLDS datasets. As noted in `regenerate_libero_dataset.py`  , the detailed of RLDS data conversion is not shown, where the images are rotated by 180 degrees before converting. May I ask how to set the rotated transform correctly during/before the RLDS conversion? 

Thanks!

**Comment by AndyCao1125** [comment]
I think I have solved this problem, thanks!

**Comment by lostgreen** [comment]
@AndyCao1125 Hi, could you please tell me how to transform libero dataset from hdf5 to rlds? Thanks a lot!

**Comment by 103240** [comment]
> 我想我已经解决了这个问题，谢谢！

请问如何转换，不胜感激！！
