### ISSUE TITLE
Clarification on the Scope of LLM.int8() Quantization

### ISSUE THREAD

**Issue by YEOMJINSEOP** [openvla/openvla#137]
Hello, thank you for sharing your wonderful work.

I would like to clarify if the LLM.int8() quantization method is applied only to the **LLM part,** or if it is also applied to **other components** such as the **Vision Encoder** and **Projection layers.**

Thank you for your time and consideration.

Best regards,
Jinseop Yeom

**Comment by kpertsch** [comment]
I believe it's only applied to the LLM backbone since it's by far the bulk of the parameters / memory / compute (7B vs 600M for the two-stream image encoders).
@siddk pls correct if this is incorrect!

**Comment by siddk** [comment]
Yes, just applied to the LLM!

**Comment by YEOMJINSEOP** [comment]
Thanks for Reply!
