### ISSUE TITLE
Cached Generation vs Multimodal Forward

### ISSUE THREAD

**Issue by YEOMJINSEOP** [openvla/openvla#148]
Hi, i observed that for each step, multiple **Cached Generation** processes are followed by a **Multimodal Forward** process in 
```
class PrimsmaticForConditionalGeneration
   def forward(...):
```

In a **Multimodal Forward** process, language_model uses multimodal_embeddings 
However in **Cached Generation**,  language_model doesn't use multimodal_embeddings.

Why do we need this process(which doesn't use multimodal_embeddings)??

- Cached Generation
```
language_model_output = self.language_model(
                input_ids=input_ids,
                attention_mask=None,
                position_ids=None,
                past_key_values=past_key_values,
                inputs_embeds=None,
                labels=None,
                use_cache=use_cache,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
                return_dict=return_dict,
)
```
- Multimodal Forward
```
language_model_output = self.language_model(
                input_ids=None,
                attention_mask=multimodal_attention_mask, 
                position_ids=None,
                past_key_values=None,
                inputs_embeds=multimodal_embeddings, 
                labels=multimodal_labels, 
                use_cache=use_cache, 
                output_attentions=output_attentions, 
                output_hidden_states=output_hidden_states,
                return_dict=return_dict,
            )
```

**Comment by jashshah999** [comment]
Late follow-up for future searchers: this code region is exactly where a real bug lives on transformers ≥4.50. `prepare_inputs_for_generation` slices the prompt whenever `past_key_values is not None`; modern transformers passes an *empty* `DynamicCache` on step 0, so the prompt collapses to one token, `forward` takes the cached branch, and `pixel_values` is never read. The model returns a constant action for every input. Diagnosis + fix: #346, shim: https://github.com/jashshah999/vla-lite
