### ISSUE TITLE
Can you realse the code and pre-trained weights of Octo on LIBERO?

### ISSUE THREAD

**Issue by Zhangwenyao1** [openvla/openvla#150]
Thanks for your excellent work ! 
Can you realse the code and pre-trained weights of Octo on LIBERO?

**Comment by moojink** [comment]
Hi @Zhangwenyao1,

We do not plan to release code/checkpoints for the baseline methods. Please refer to the official repos for fine-tuning instructions for Octo ([here](https://github.com/octo-models/octo)) and Diffusion Policy ([here](https://github.com/real-stanford/diffusion_policy) or [here](https://github.com/droid-dataset/droid_policy_learning); we used the latter for a language-conditioned implementation). For Octo, you can see Karl's response for tips on reproducing the results here: https://github.com/openvla/openvla/issues/129#issuecomment-2402501895

-Moo Jin
