### ISSUE TITLE
Inference by the model downloaded from hf

### ISSUE THREAD

**Issue by qingshi666666** [openvla/openvla#160]
i want to inference by the model downloaded from hf (openvla/openvla-7b-finetuned-libero-10) ,can you write a example .the robot is urd5

**Comment by kpertsch** [comment]
Please note that the libero finetuned model will only work on libero as the test environment. If you want to run OpenVLA on a new robot, you need to finetune it on data from your new robot.
For an example how to inference OpenVLA models, please check out the deploy.py script and the Bridge robot example!
