### ISSUE TITLE
LIBERO dependency on robosuite v1.4

### ISSUE THREAD

**Issue by donovanclay** [openvla/openvla#163]
I am trying to run the LIBERO evaluations (specifically `LIBERO-Goal`) and got this error:
```
ModuleNotFoundError: No module named 'robosuite.environments.manipulation.single_arm_env'
```
It seems like in robosuite [v1.5](https://github.com/ARISE-Initiative/robosuite/tree/v1.5.0/robosuite/environments/manipulation) the `single_arm_env.py` file is no longer present. [v1.4](https://github.com/ARISE-Initiative/robosuite/tree/v1.4/robosuite/environments/manipulation) includes it. The `libero_requirements.txt` doesn't specify a specific version. It seems like I can run the evaluation just fine after uninstalling `robosuite` and reinstalling the 1.4 version

**Comment by moojink** [comment]
Hi @donovanclay,

Thank you so much for raising this issue. Indeed, the version update in robosuite is causing that error. Just pushed a [commit](https://github.com/openvla/openvla/commit/e2929881bb544d53b1a5b6c3e7d4bddd7fbf6bd9) that pins the robosuite version (to v1.4.1, which is what we used in our LIBERO experiments) in `libero_requirements.txt`. This should prevent future users from encountering the error.

Cheers!

-Moo Jin
