### ISSUE TITLE
validation on BridgeDataV2

### ISSUE THREAD

**Issue by xwz-z** [openvla/openvla#170]
Hi!
Thank you for opening the code for evaluation.
I would like to ask if the verification of bridge data v2 needs to be verified on the actual machine, because I will get a prompt during the operation: `bridge data cannot open device /dev/video0, exiting.`
In addition, on which simulation platform can the verification of bridge data v2 be run? Can you provide relevant information?

In addition, can OpenVLA be used for general communication, in addition to just outputting actions?

Thanks in advance! Or is there anyone willing to answer this question, Thanks!

**Comment by kpertsch** [comment]
Sorry, it's a bit hard to debug the failure you're observing without more information. Can you post the command you are running and a full stack trace of your error?

Re testing OpenVLA: if you don't have a physical Bridge robot setup, you could try running on the SIMPLER simulated eval environment: https://simpler-env.github.io/, though we had mixed results with OpenVLA in this environment in the past.

Re general question answering: OpenVLA is only finetuned with robot action data, so it looses its ability to answer text questions with text responses in that process. We have tested co-training OpenVLA with VLM training data (eg you can check out how Prismatic VLM trains with VLM data) and in this case, the model does retain chat ability.

**Comment by kpertsch** [comment]
Got it -- for the error you're getting you should probably raise it in the BridgeDataV2 repo, since it seems related to Bridge-hardware specific issues, not OpenVLA.

Re platform for eval: you can check out the Libero examples we have in this repo -- it's a simulated eval and OpenVLA should work well on it.
