### ISSUE TITLE
Will OpenVLLA integrate with vLLM for inference acceleration?

### ISSUE THREAD

**Issue by choucaicai** [openvla/openvla#171]
Currently, inferencing a single episode takes a very long time. I'm wondering if there are plans to integrate OpenVLLA with vLLM in the future to help accelerate the inference process?

**Comment by kpertsch** [comment]
Here is an example of loading OpenVLA with TensorRT-LLM for substantial inference acceleration on certain GPU hardware: https://github.com/rail-berkeley/tensorrt-openvla

**Comment by LukeLIN-web** [comment]
vllm should be beneficial for very large batch inference, maybe not suitable for robot case.
