### ISSUE TITLE
Does OpenVLA support training on  Ascend NPU?

### ISSUE THREAD

**Issue by 121209** [openvla/openvla#173]
I want to train openvla on Ascend NPU to make a demo for developer.Does OpenVLA support training on  Ascend NPU?

**Comment by kpertsch** [comment]
We have not tested OpenVLA on that computing platform. It seems that there is a pytorch port for Ascend NPUs, so you could try your luck whether using it will just work out of the box, but we can unfortunately not provide support for this.
