### ISSUE TITLE
Confusion about "10 tasks x 500 episodes each".

### ISSUE THREAD

**Issue by ZihengQiu** [openvla/openvla#178]
I've noticed that the following states there are **500** episodes for each task in the LIBERO evaluation section from README.md:
> The evaluation script will run **500** trials by default (**10** tasks x **500** episodes each).

However, it appears there are actually **500** trials in total for the evaluation script. Could you please clarify if this is an oversight, or if I am misunderstanding the information provided?

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

The README.md file incorrectly states that the evaluation script runs 500 episodes per task, while the actual implementation in run_libero_eval.py shows 50 episodes per task. We'll update the README to reflect the correct information.

You can review changes in this commit: https://github.com/kkpo4553/openvla-openvla-178/commit/326d16e0eeaafedf4444684dc02dfaff36dae7d3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by moojink** [comment]
Hi @ZihengQiu,

Thank you for catching that! Yes, it should say "10 tasks x 50 episodes each" for a total of 500 episodes. We just updated the README.

-Moo Jin
