### ISSUE TITLE
get_openvla_prompt ablations and deploy details.

### ISSUE THREAD

**Issue by willxxy** [openvla/openvla#18]
Hello,

Thank you for the great works. 

1) I had a question out of curiosity if there has been any ablation studies you did in regards to the system prompt in `openvla/vla-scripts/deploy.py` lines 58 - 62. From my understanding, it seems only this prompt of f"{SYSTEM_PROMPT} USER: What action should the robot take to {instruction.lower()}? ASSISTANT:" or f"In: What action should the robot take to {instruction.lower()}?\nOut:", where 

`SYSTEM_PROMPT = ("A chat between a curious user and an artificial intelligence assistant. " "The assistant gives helpful, detailed, and polite answers to the user's questions.")`

were tested. 

If you could expand on the sensitivity of the model's performance wrt the system prompt it would be great!

2) Additionally, in the Getting Started code snippet in the README page

```
# Install minimal dependencies (`torch`, `transformers`, `timm`, `tokenizers`, ...)
# > pip install -r https://raw.githubusercontent.com/openvla/openvla/main/requirements-min.txt
from transformers import AutoModelForVision2Seq, AutoProcessor
from PIL import Image

import torch

# Load Processor & VLA
processor = AutoProcessor.from_pretrained("openvla/openvla-7b", trust_remote_code=True)
vla = AutoModelForVision2Seq.from_pretrained(
    "openvla/openvla-7b", 
    attn_implementation="flash_attention_2",  # [Optional] Requires `flash_attn`
    torch_dtype=torch.bfloat16, 
    low_cpu_mem_usage=True, 
    trust_remote_code=True
).to("cuda:0")

# Grab image input & format prompt
image: Image.Image = get_from_camera(...)
prompt = "In: What action should the robot take to {<INSTRUCTION>}?\nOut:"

# Predict Action (7-DoF; un-normalize for BridgeData V2)
inputs = processor(prompt, image).to("cuda:0", dtype=torch.bfloat16)
action = vla.predict_action(**inputs, unnorm_key="bridge_orig", do_sample=False)

# Execute...
robot.act(action, ...)
```

 I was wondering why the prompt did not have the SYSTEM_PROMPT?
 
3)  Lastly, could you please clarify whether the given logic is correct for deployment?

```
instruction = 'pick up cup'
prompt = f"{SYSTEM_PROMPT} USER: What action should the robot take to {instruction.lower()}?
while rollout True
     image: Image.Image = get_from_camera(...)   
     inputs = processor(prompt, image).to("cuda:0", dtype=torch.bfloat16)
     action = vla.predict_action(**inputs, unnorm_key="bridge_orig", do_sample=False)
     if success:
           break
```

Thank you.

**Comment by willxxy** [comment]
Another update to this issue. For questions 1 and 2, from my experience, it seems like for inference, f"{SYSTEM_PROMPT} USER: What action should the robot take to {instruction.lower()}? ASSISTANT:" or f"In: What action should the robot take to {instruction.lower()}?\nOut:" does not really give different performance. Is this a normal behavior?

**Comment by moojink** [comment]
Hi @willxxy,

Thank you for reaching out. Here are answers to your questions:

> I had a question out of curiosity if there has been any ablation studies you did in regards to the system prompt in openvla/vla-scripts/deploy.py lines 58 - 62.

1. We have not tried altering the system prompt in our experiments. We simply chose to use the same system prompt used by the base Prismatic VLM. The reason for this is that if the VLM has always seen the same system prompt during the pretraining phase, then changing the system prompt during fine-tuning or inference would introduce distribution shift with respect to the training data, which would not be ideal.

Note: The system prompts for the main OpenVLA model ([openvla-7b](https://huggingface.co/openvla/openvla-7b)) and the early development model ([openvla-v01-7b](https://huggingface.co/openvla/openvla-v01-7b)) differ. If using the main model, you should use the prompt structure `f"In: What action should the robot take to {instruction.lower()}?\nOut:"`. If using the early development model, you should use `f"{SYSTEM_PROMPT} USER: What action should the robot take to {instruction.lower()}? ASSISTANT:"`, where `SYSTEM_PROMPT == "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions."` These are the system prompts used by the respective base VLMs.

> Additionally, in the Getting Started code snippet in the README page
> I was wondering why the prompt did not have the SYSTEM_PROMPT?

2. The "Note" in my answer above addresses this. The [openvla-7b](https://huggingface.co/openvla/openvla-7b) model was not pretrained with that `SYSTEM_PROMPT` (including the base Prismatic VLM), so you should omit it when running inference with that model.

> Lastly, could you please clarify whether the given logic is correct for deployment?

3. If using the [openvla-7b](https://huggingface.co/openvla/openvla-7b) model, you would need to change the system prompt to match the Getting Started code snippet. Aside from that, the overall structure of your code snippet looks right to me!

> Another update to this issue. For questions 1 and 2, from my experience, it seems like for inference, f"{SYSTEM_PROMPT} USER: What action should the robot take to {instruction.lower()}? ASSISTANT:" or f"In: What action should the robot take to {instruction.lower()}?\nOut:" does not really give different performance. Is this a normal behavior?

That is surprising to me, given that you are changing the tokens that are being fed into the model. Perhaps you observed similar performance for some narrow dataset/example, but I would not expect this to hold in general. I would recommend that you use the correct system prompt to avoid distribution shift.

Hope that helps!
-Moo Jin
