### ISSUE TITLE
Finetuning OpenVLA on a custom dataset with a different state and and action encoding scheme

### ISSUE THREAD

**Issue by rajas1310** [openvla/openvla#180]
I want to finetune OpenVLA on a custom dataset with a different state and and action encoding scheme.

My action space is a 1D value and I have made the required changes to the `transforms.py` script.
But the code raised an error 
>``` if dataset_kwargs["action_encoding"] not in [ActionEncoding.EEF_POS, ActionEncoding.EEF_R6]:```
>```        raise ValueError(f"Cannot load `{dataset_name}`; only EEF_POS & EEF_R6 actions supported!")```

I did not understand how to use a custom action encoding or what can be edited so that the code supports the my custom action encoding. 
Kindly help me with this issue. Thank you.

**Comment by kpertsch** [comment]
Ah you can just hack around that ValueError. Just define a new action mask in the lines below the value error for your type of action encoding, then add it to the "not in" list so it does not throw an error anymore -- should work!
