### ISSUE TITLE
Results on RLbench

### ISSUE THREAD

**Issue by ustcwhy** [openvla/openvla#19]
Thanks for your wonderful work, and open-sourcing the code, model and data of OpenVLA!

I try to evaluate the OpenVLA on RLbench, but the results seem not very good (0 acc on most of the tasks). 
OpenVLA seems very hard to generalize across different environments and robots.

Do you have any results on the simulation platforms, such as RLbench, which is better for fair comparision

**Comment by kpertsch** [comment]
Hi!
Thanks for giving OpenVLA a try! RLBench was not part of our training dataset, so it's unlikely OpenVLA will work out of the box.
As a general rule of thumb, the model will work out of the box for datasets featured in the training mix -- for any other environment, like RL Bench, it will require finetuning with some target domain data.
So if you want to test RL bench, you can use `finetune.py` with some RL bench data to get the model to work in that domain!
