### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Ye13ow77z** [openvla/openvla#22]
How can I download the dataset used for training？I cant figure out followed the explanation in your github..

**Comment by Ye13ow77z** [comment]
emmm I think I have overcome this but... how to solve“ModuleNotFoundError: No module named 'prismatic.conf'”

**Comment by siddk** [comment]
Can you run an editable install of the repository (via `pip install -e .` from the root of the repo)?

**Comment by moojink** [comment]
Closing the issue; feel free to reopen if the issue is not resolved.
