### ISSUE TITLE
About Hardware

### ISSUE THREAD

**Issue by yangwangopen** [openvla/openvla#23]
How to purchase the corresponding hardware in the demonstration?

![image](https://github.com/openvla/openvla/assets/64902516/e872f53b-0aba-4d0f-a569-753725ff524f)
![image](https://github.com/openvla/openvla/assets/64902516/438307c5-e173-45bd-a0d9-3b475772db8e)
![image](https://github.com/openvla/openvla/assets/64902516/a01bd7f2-ff23-4612-901a-a49e66b8e19d)

Or do you have any recommendations for other hardware to purchase?

**Comment by kpertsch** [comment]
For the Bridge setup in the first picture, you can find a hardware setup guide here: https://docs.google.com/document/d/1si-6cTElTWTgflwcZRPfgHU7-UwfCUkEztkH3ge5CGc/edit

For a Franka setup comparable to the second picture, there's a hardware setup guide here: https://droid-dataset.github.io/droid/docs/hardware-setup 

The Google robot in the third image is not currently purchasable.

**Comment by Boltzmachine** [comment]
If I set up the image acquisition myself, how can I ensure that the image distribution remains consistent and is not affected by environmental factors like lighting? Or is this something people generally don't pay much attention to?
