### ISSUE TITLE
About Delta Output

### ISSUE THREAD

**Issue by JianJianHeng** [openvla/openvla#35]
Hello, Author,

I have a question regarding the output of OpenVLA. Is the output always in relative terms? I noticed that the Open X Embodiment dataset contains both absolute and relative positions. I am seeking advice from the authors on how to handle the absolute and relative values within the dataset effectively.

Could you please provide some guidance or suggestions on this matter?
Thank you for your time and assistance.

**Comment by kpertsch** [comment]
Hi!

We are using delta actions for all datasets in translation and rotation dimensions. For the gripper action dimension we always use absolute actions.
In principle, it's no problem to mix in / fine-tune with an absolute control dataset -- there would be some domain shift to the pre-training data, but with enough fine-tuning data I would assume that the model should be able to adapt to absolute actions and there should hopefully still be positive transfer from the pre-training data. (though we have never tested this ourselves)
