### ISSUE TITLE
About deployment

### ISSUE THREAD

**Issue by ZhenpengChenCode** [openvla/openvla#36]
Thank you for open sourcing your code!
May I ask what platform your code is deployed on? What frame rate was achieved?

**Comment by kpertsch** [comment]
We deployed our policies on various platforms (please see our paper): two different Franka robots, a WidowX robot and the Google robot. 
For frame rate, we achieved approximately 6 Hz on a 4090 GPU (again see paper for a detailed plot of achievable control frequencies on different GPUs)
