### ISSUE TITLE
Can this source code be reproduced on windows?

### ISSUE THREAD

**Issue by ShaunMaple** [openvla/openvla#41]
Can this source code be reproduced on windows?

**Comment by kpertsch** [comment]
I don't have experience running deep learning code on Windows. 
The main packages we are using are PyTorch, transformers and flash attention. As long as you can get these to run on your Windows system, the fine-tuning script should hopefully run, but this is not something we have tested. If you can verify that these three packages work correctly on your system, but you still have issues running the fine-tuning script, feel free to reopen this issue!
