### ISSUE TITLE
input robot's continuous camera stream?

### ISSUE THREAD

**Issue by ramkumarkoppu** [openvla/openvla#51]
By looking at the provided example https://github.com/openvla/openvla#getting-started
it appears it' taking single capture of the robot camera, Is it possible input robot's continuous camera stream for robot actions predictions without fine tuning the model?

**Comment by kpertsch** [comment]
Hi!

The model predicts a single action given a single input image from the camera. You can continuously feed camera images into the model and it will continuously predict actions, but each action prediction will only be based on the most recent camera frame. I hope this answers your question!
Re using it without finetuning: the current model will only work reasonably without finetuning if you reproduce one of the training setups quite closely, so most likely some finetuning data will be required to get the model adapted to your robot setup. See our README for instructions how to finetune the model!
