### ISSUE TITLE
how much memory is needed to run this model?

### ISSUE THREAD

**Issue by yxchng** [openvla/openvla#57]
I tried RTX3090 and 40GB A100, both go out of memory.

**Comment by kpertsch** [comment]
Are you asking about inference or about training?
For inference you only need 11GB in `bfloat16` precision -- down to 6GB if you use 4bit quantization.
For training it depends. If you want to do full finetuning you will need 2+ 80GB GPUs. However, if you use our LoRA finetuning script you should be able to fit things on a 40GB A100 with a sufficiently small batch size (start with batch size 1, then go up)
