### ISSUE TITLE
Multiple episodes from different datasets

### ISSUE THREAD

**Issue by ymxlzgy** [openvla/openvla#59]
Hi, I saw you have an instance `EpisodicRLDSDataset` of how to load episodes from one dataset. However, I want to load mixed episodes from multiple datasets, could you elaborate me more on this? Thanks!!

**Comment by kpertsch** [comment]
The EpisodicRLDSDataset does not currently support loading from multiple datasets -- it's not made for training. If you really want to sample at random from multiple datasets you can just make N separate datasets and sample with a separate random process?
