### ISSUE TITLE
How to evaluate on a headless machine?

### ISSUE THREAD

**Issue by betray12138** [openvla/openvla#70]
Thank you for open-sourcing your evaluation code! I greatly appreciate it. However, please tell me how to evaluate the model on a headless machine and what the evaluation metric is, which I don't see in the run_bridgev2_eval.py.

**Comment by kpertsch** [comment]
Thanks for reaching out!
I am a bit confused about your question -- the model can run on a headless server no problem, the question is just what images you feed into the model. The model is usually evaluated by rolling out the predicted actions on a real robot system.
