### ISSUE TITLE
Evaluation on public benchmark, e.g., SimplerEnv

### ISSUE THREAD

**Issue by DelinQu** [openvla/openvla#8]
Thank you for the open-source project 🤗. This will be a significant advancement for general robotic systems! Additionally, I would like to ask if the author or anyone else has evaluated openvla on public benchmarks, e.g., SimplerEnv [SimplerEnv](https://github.com/simpler-env/SimplerEnv)? Could you share the evaluation results? Thanks!  😊

**Comment by siddk** [comment]
We don't have complete results yet -- but see #7 for an issue tracking this!
