### ISSUE TITLE
Performance about Training VLAs on Bridge V2 from Scratch

### ISSUE THREAD

**Issue by hutchinsonian** [openvla/openvla#80]
Thank you so much for such a great job!
The article mentioned that you only trains on the bridge dataset for fast iteration. 
How is the performance and score of the model trained on a small dataset? 
I want to reproduce this result, but I don't know how effective it is to train from scratch on the bridgev2 dataset only. 
I found that after one epoch, the action accuracy is only around 0.15. 
How did you perform during training? Have I overlooked something?

**Comment by kpertsch** [comment]
Hey thanks for reaching out!
BridgeV2 is large + diverse enough that OpenVLA models trained only on BridgeV2 work pretty well, so it's a good dataset for faster iteration!
Your observation makes sense tho -- we typically see that we need to train quite a few epochs on a dataset to get high action accuracy -- I would expect approx 80k iterations @ 256 batch size for Bridge to converge to 95%+ action accuracy!
