### ISSUE TITLE
 Task failures in LIBERO simulation when Running evaluation code

### ISSUE THREAD

**Issue by shifsa** [openvla/openvla#92]
Thanks for releasing such source code!　
To check the operation in my environment, I ran the evaluation code for the OpenVLA model (openvla-7b-finetuned-libero-spatial) on the libero_spatial task suite. 
But all tasks fail, resulting in a 0% success rate.
Do you know what could be causing this problem?

Environment:

- OS: Ubuntu20.04
- RAM: 64GB
- CPU: Intel(R) Core(TM) i9-10900X
- GPU: Quadro RTX 8000
- CUDA version: 12.0

Error Log:

```
(openvla) linux:~/openvla$ python experiments/robot/libero/run_libero_eval.py --model_family openvla --pretrained_checkpoint openvla/openvla-7b-finetuned-libero-spatial --task_suite_name libero_spatial --center_crop True
2024-09-06 18:39:17.012547: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-06 18:39:17.056315: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-06 18:39:17.056352: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-06 18:39:17.057530: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-06 18:39:17.064988: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/shimizke/miniconda3/envs/openvla/lib/python3.10/site-packages/robosuite/scripts/setup_macros.py (macros.py:55)
[*] Instantiating Pretrained VLA model
[*] Loading in BF16 with Flash-Attention Enabled
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
dWARNING: No local dataset_statistics.json file found for current checkpoint.
You can ignore this if you are loading the base VLA (i.e. not fine-tuned) checkpoint.Otherwise, you may run into errors when trying to call `predict_action()` due to an absent `unnorm_key`.
Loaded model: <class 'transformers_modules.openvla.openvla-7b.e5822cc24559b04e532f49b1c1ddb64376c1a485.modeling_prismatic.OpenVLAForActionPrediction'>
Logging to local log file: ./experiments/logs/EVAL-libero_spatial-openvla-2024_09_06-18_39_45.txt
[info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Task suite: libero_spatial
  0%|                                                                                                       | 0/10 [00:00<?, ?it/s]
Task: pick up the black bowl between the plate and the ramekin and place it on the plate                    | 0/50 [00:00<?, ?it/s]
Starting episode 1...
Caught exception: FlashAttention only supports Ampere GPUs or newer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=1--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
Success: False
# episodes completed so far: 1
# successes: 0 (0.0%)

Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 1/50 [00:03<02:35,  3.17s/it]
Starting episode 2...
Caught exception: FlashAttention only supports Ampere GPUs or newer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=2--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
Success: False
# episodes completed so far: 2
# successes: 0 (0.0%)

Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 2/50 [00:05<01:55,  2.42s/it]
Starting episode 3...
Caught exception: FlashAttention only supports Ampere GPUs or newer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=3--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
Success: False
# episodes completed so far: 3
# successes: 0 (0.0%)

Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 3/50 [00:06<01:40,  2.14s/it]
Starting episode 4...
Caught exception: FlashAttention only supports Ampere GPUs or newer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=4--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
Success: False
# episodes completed so far: 4
# successes: 0 (0.0%)

Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 4/50 [00:08<01:32,  2.01s/it]
Starting episode 5...
Caught exception: FlashAttention only supports Ampere GPUs or newer.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=5--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
Success: False
# episodes completed so far: 5
# successes: 0 (0.0%)
```

**Comment by LemonZhong** [comment]
Do you have this problem?
(base) wy@huang-ESC8000-G4:/home/data/wy/znz/openvla$ python experiments/robot/libero/run_libero_eval.py \
>   --model_family openvla \
>   --pretrained_checkpoint openvla/openvla-7b-finetuned-libero-object \
>   --task_suite_name libero_object \
>   --center_crop True
Traceback (most recent call last):
  File "/media/wy/znz/openvla/experiments/robot/libero/run_libero_eval.py", line 26, in <module>
    import draccus
ModuleNotFoundError: No module named 'draccus'

I have :
Clone and install the [LIBERO repo](https://github.com/Lifelong-Robot-Learning/LIBERO):

git clone https://github.com/Lifelong-Robot-Learning/LIBERO.git
cd LIBERO
pip install -e .
Additionally, install other required packages:

cd openvla
pip install -r experiments/robot/libero/libero_requirements.txt

**Comment by LemonZhong** [comment]
I have solved my problem

**Comment by prilgrim-whtie** [comment]
> Thanks for releasing such source code!　 To check the operation in my environment, I ran the evaluation code for the OpenVLA model (openvla-7b-finetuned-libero-spatial) on the libero_spatial task suite. But all tasks fail, resulting in a 0% success rate. Do you know what could be causing this problem?
> 
> Environment:
> 
> * OS: Ubuntu20.04
> * RAM: 64GB
> * CPU: Intel(R) Core(TM) i9-10900X
> * GPU: Quadro RTX 8000
> * CUDA version: 12.0
> 
> Error Log:
> 
> ```
> (openvla) linux:~/openvla$ python experiments/robot/libero/run_libero_eval.py --model_family openvla --pretrained_checkpoint openvla/openvla-7b-finetuned-libero-spatial --task_suite_name libero_spatial --center_crop True
> 2024-09-06 18:39:17.012547: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 2024-09-06 18:39:17.056315: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
> 2024-09-06 18:39:17.056352: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
> 2024-09-06 18:39:17.057530: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 2024-09-06 18:39:17.064988: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> [robosuite WARNING] No private macro file found! (macros.py:53)
> [robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
> [robosuite WARNING] To setup, run: python /home/shimizke/miniconda3/envs/openvla/lib/python3.10/site-packages/robosuite/scripts/setup_macros.py (macros.py:55)
> [*] Instantiating Pretrained VLA model
> [*] Loading in BF16 with Flash-Attention Enabled
> <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.09it/s]
> dWARNING: No local dataset_statistics.json file found for current checkpoint.
> You can ignore this if you are loading the base VLA (i.e. not fine-tuned) checkpoint.Otherwise, you may run into errors when trying to call `predict_action()` due to an absent `unnorm_key`.
> Loaded model: <class 'transformers_modules.openvla.openvla-7b.e5822cc24559b04e532f49b1c1ddb64376c1a485.modeling_prismatic.OpenVLAForActionPrediction'>
> Logging to local log file: ./experiments/logs/EVAL-libero_spatial-openvla-2024_09_06-18_39_45.txt
> [info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
> Task suite: libero_spatial
>   0%|                                                                                                       | 0/10 [00:00<?, ?it/s]
> Task: pick up the black bowl between the plate and the ramekin and place it on the plate                    | 0/50 [00:00<?, ?it/s]
> Starting episode 1...
> Caught exception: FlashAttention only supports Ampere GPUs or newer.
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=1--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
> Success: False
> # episodes completed so far: 1
> # successes: 0 (0.0%)
> 
> Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 1/50 [00:03<02:35,  3.17s/it]
> Starting episode 2...
> Caught exception: FlashAttention only supports Ampere GPUs or newer.
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=2--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
> Success: False
> # episodes completed so far: 2
> # successes: 0 (0.0%)
> 
> Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 2/50 [00:05<01:55,  2.42s/it]
> Starting episode 3...
> Caught exception: FlashAttention only supports Ampere GPUs or newer.
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=3--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
> Success: False
> # episodes completed so far: 3
> # successes: 0 (0.0%)
> 
> Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 3/50 [00:06<01:40,  2.14s/it]
> Starting episode 4...
> Caught exception: FlashAttention only supports Ampere GPUs or newer.
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=4--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
> Success: False
> # episodes completed so far: 4
> # successes: 0 (0.0%)
> 
> Task: pick up the black bowl between the plate and the ramekin and place it on the plate            | 4/50 [00:08<01:32,  2.01s/it]
> Starting episode 5...
> Caught exception: FlashAttention only supports Ampere GPUs or newer.
> huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
> To disable this warning, you can either:
> 	- Avoid using `tokenizers` before the fork if possible
> 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
> Saved rollout MP4 at path ./rollouts/2024_09_06/2024_09_06-18_39_45--episode=5--success=False--task=pick_up_the_black_bowl_between_the_plate_and_the_r.mp4
> Success: False
> # episodes completed so far: 5
> # successes: 0 (0.0%)
> ```

I had the same problem as you.How did you solve it

**Comment by Lewis-Lu** [comment]
Same here, but I'm wondering how the flash_attn_2 would affect the success rate ? Would slight change in output of LLM would affect the action accuracy ?

Best,
Lewis
