### ISSUE TITLE
BridgeData V2 WidowX Evaluations

### ISSUE THREAD

**Issue by prilgrim-whtie** [openvla/openvla#95]
Thank you for open-sourcing the VLA. I am new to robotic models and I do not have a physical robot.I would like to ask, in BridgeData V2 WidowX Evaluations experiments, are real robots and environments used, or are simulations used.

**Comment by kpertsch** [comment]
We used the real robot setups from the BridgeV2 paper: https://rail-berkeley.github.io/bridgedata/
Their repo has some documentation on how to set up a real robot eval scene that matches theirs.
