### ISSUE TITLE
Fine tune pipeline for LIBERO

### ISSUE THREAD

**Issue by jbonobono** [openvla/openvla#99]
Hello,
thank you for your great work openvla and recent update for LIBERO fine-tune model and eval pipeline

if possible, would you please share also fine tune pipeline for LIBERO? which can re-generate uploaded  LIBERO fine-tune model.

since I  want to do more experiment on LIBERO with backbone openvla, 
wanted to start same baseline as yours. if possible.

hope I can have your feedback

have a nice day
thank you

**Comment by kpertsch** [comment]
We registered the LIBERO dataset in our codebase: https://github.com/openvla/openvla/blob/7a359de9bb8be6fd3c232d189784920dbc93391c/prismatic/vla/datasets/rlds/oxe/mixtures.py#L196

So you can download them from huggingface (https://huggingface.co/datasets/openvla/modified_libero_rlds) and then just run our default finetuning script, just make sure to set `--dataset_name` to the libero dataset you want to use!

**Comment by jbonobono** [comment]
thanks a lot !

**Comment by jis3613** [comment]
Hi, I'm trying to finetune the openvla on libero dataset you provided.

However, I constantly get the following error.
`tensorflow_datasets.core.registered.DatasetNotFoundError: Dataset libero_spatial_no_noops not found`
It seems like the libero dataset you modified in rlds format is not registered in the tfds.

Or is there additional steps that I need to follow ?

Your answer would be a great help to me.
Thanks!

**Comment by Sprinter1999** [comment]
> Hi, I'm trying to finetune the openvla on libero dataset you provided.
> 
> However, I constantly get the following error. `tensorflow_datasets.core.registered.DatasetNotFoundError: Dataset libero_spatial_no_noops not found` It seems like the libero dataset you modified in rlds format is not registered in the tfds.
> 
> Or is there additional steps that I need to follow ?
> 
> This is the script I ran. `gpu_id=1,2,3,4,5,6,7 CUDA_VISIBLE_DEVICES=${gpu_id} torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \ --vla_path openvla/openvla-7b \ --data_root_dir datasets \ --dataset_name libero_spatial_no_noops \ --run_root_dir runs \ --adapter_tmp_dir adapter_tmp_weights \ --lora_rank 32 \ --batch_size 4 \ --grad_accumulation_steps 4 \ --learning_rate 5e-4 \ --image_aug True \ --save_steps 5000 \`
> 
> datasets dir is located under openvla and libero_spatial_no_noops is located under datasts so, `/openvla/datasets/libero_spatial_no_noops`
> 
> Your answer would be a great help to me. [@kpertsch](https://github.com/kpertsch) [@moojink](https://github.com/moojink) Thanks!

Perhaps you can use the converted dataset version like this:
```
  --data_root_dir /root/autodl-tmp/datasets/modified_libero_rlds \
  --dataset_name libero_spatial_no_noops \
```
